name: Java Maven Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven

    - name: Get Maven project version
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_ENV

    - name: Delete old package versions (keeping only latest)
      run: |
        PACKAGE_NAME="api.commond"
        OWNER="cmsystem"
        PACKAGE_TYPE="maven"
        TOKEN=$GITHUB_TOKEN
    
        echo "Fetching package versions for $PACKAGE_NAME..."
    
        # Para debug temporal, ver respuesta
        curl -s -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/orgs/$OWNER/packages/$PACKAGE_TYPE/$PACKAGE_NAME/versions > response.json
        cat response.json
    
        # Cambia orgs por users si OWNER es usuario:
        # https://api.github.com/users/$OWNER/packages/$PACKAGE_TYPE/$PACKAGE_NAME/versions
    
        VERSIONS=$(jq '.package_versions[].id' response.json)
    
        COUNT=0
        for VERSION_ID in $VERSIONS; do
          COUNT=$((COUNT+1))
          if [ "$COUNT" -gt 1 ]; then
            echo "Deleting version ID: $VERSION_ID"
            curl -s -X DELETE -H "Authorization: Bearer $TOKEN" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/orgs/$OWNER/packages/$PACKAGE_TYPE/$PACKAGE_NAME/versions/$VERSION_ID
          fi
        done
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

    - name: Publicando el paquete en GitHub
      run: mvn clean deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/cmsystem/CMSystemCApiCommond
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
