name: Java Maven Deploy
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'microsoft'
        cache: maven
    - name: publicando el paquete en GitHub
      run: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/cmsystem/CMSystemCApiCommond
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
    - name: Get Maven project version
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_ENV